DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS lobby;
DROP TABLE IF EXISTS game;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE media (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE lobby (
  code INTEGER PRIMARY KEY  NOT NULL,
  players TEXT NOT NULL,
  started BOOL NOT NULL,
  game_code INTEGER NOT NULL
);

CREATE TABLE game (
  uuid TEXT NOT NULL,
  players TEXT NOT NULL,
  rolls TEXT NOT NULL,
  messages TEXT NOT NULL
);
